apiVersion: kubeopencode.io/v1alpha1
kind: Agent
metadata:
  name: opencode-agent
  namespace: kubeopencode-default
spec:
  config:
    $schema: https://opencode.ai/config.json
    model: opencode/big-pickle
    provider:
      opencode:
        options:
          apiKey: "{env:OPENCODE_API_KEY}"
  credentials:
    - name: opencode
      secretRef:
        name: opencode-credentials
  workspaceDir: /workspace
  serviceAccountName: opencode-agent